<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Amber.Domain\Amber.Domain.csproj" />
    <ProjectReference Include="..\Amber.Application\Amber.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="EntityFrameworkCore.Exceptions.PostgreSQL" />
    <PackageReference Include="FlexLabs.EntityFrameworkCore.Upsert" />
    <PackageReference Include="Google.Apis.Auth" />
    <PackageReference Include="LettermintDotNet" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
</Project>
