<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Amber.Domain\Amber.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference
      Include="LiteBus.Commands.Extensions.Microsoft.DependencyInjection"
      Version="6.0.2"
    />
    <PackageReference
      Include="LiteBus.Queries.Extensions.Microsoft.DependencyInjection"
      Version="6.0.2"
    />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <None Include="StaticFiles\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
