// <auto-generated />
using System;
using Amber.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Amber.Infrastructure.Migrations
{
    [DbContext(typeof(AmberContext))]
    [Migration("20260816160227_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Amber.Domain.Sync.Entities.SyncCell", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Table")
                        .HasColumnType("text")
                        .HasColumnName("tbl");

                    b.Property<string>("RowId")
                        .HasColumnType("text")
                        .HasColumnName("row_id");

                    b.Property<string>("Column")
                        .HasColumnType("text")
                        .HasColumnName("col");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ServerSeq")
                        .HasColumnType("bigint");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Value")
                        .HasColumnType("bytea");

                    b.Property<DateTime>("WrittenAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("UserId", "Table", "RowId", "Column");

                    b.HasIndex("UserId", "ServerSeq");

                    b.HasIndex("UserId", "WrittenAt");

                    b.ToTable("sync_cells", (string)null);
                });

            modelBuilder.Entity("Amber.Domain.Users.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastDateTimeOfSentVerificationCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("SignOutDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasDatabaseName("users_google_id_index")
                        .HasFilter("\"GoogleId\" IS NOT NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Amber.Domain.Sync.Entities.SyncCell", b =>
                {
                    b.HasOne("Amber.Domain.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Amber.Domain.Sync.ValueObjects.Hlc", "Hlc", b1 =>
                        {
                            b1.Property<Guid>("SyncCellUserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("SyncCellTable")
                                .HasColumnType("text");

                            b1.Property<string>("SyncCellRowId")
                                .HasColumnType("text");

                            b1.Property<string>("SyncCellColumn")
                                .HasColumnType("text");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Hlc");

                            b1.HasKey("SyncCellUserId", "SyncCellTable", "SyncCellRowId", "SyncCellColumn");

                            b1.ToTable("sync_cells");

                            b1.WithOwner()
                                .HasForeignKey("SyncCellUserId", "SyncCellTable", "SyncCellRowId", "SyncCellColumn");
                        });

                    b.Navigation("Hlc")
                        .IsRequired();
                });

            modelBuilder.Entity("Amber.Domain.Users.Entities.User", b =>
                {
                    b.OwnsOne("Amber.Domain.Users.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("users_email_index");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Amber.Domain.Users.ValueObjects.EmailVerificationCode", "EmailVerificationCode", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("EmailVerificationCode");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Amber.Domain.Users.ValueObjects.HashedPassword", "Password", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(72)
                                .HasColumnType("character varying(72)");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Amber.Domain.Users.ValueObjects.Username", "Username", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("Username");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("users_username_index");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("EmailVerificationCode")
                        .IsRequired();

                    b.Navigation("Password");

                    b.Navigation("Username")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
