<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <UserSecretsId>b710b569-a920-4cdc-92df-302b4736e69b</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="10.2.1" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.2.1" />
    <PackageReference Include="AsyncKeyedLock" Version="8.0.2" />
    <PackageReference Include="Azure.Identity" Version="1.20.0" />
    <PackageReference Include="Grafana.OpenTelemetry" Version="1.7.0" />
    <PackageReference
      Include="LiteBus.Commands.Extensions.Microsoft.DependencyInjection"
      Version="4.3.0"
    />
    <PackageReference
      Include="LiteBus.Queries.Extensions.Microsoft.DependencyInjection"
      Version="4.3.0"
    />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.14.15">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Brainy.Infrastructure\Brainy.Infrastructure.csproj" />
    <ProjectReference Include="..\Brainy.Domain\Brainy.Domain.csproj" />
    <ProjectReference Include="..\Brainy.Application\Brainy.Application.csproj" />
  </ItemGroup>
  <Target Name="Husky" BeforeTargets="Restore;CollectPackageReferences" Condition="'$(HUSKY)' != 0">
    <Exec
      Command="dotnet tool restore"
      StandardOutputImportance="Low"
      StandardErrorImportance="High"
    />
    <Exec
      Command="dotnet husky install"
      StandardOutputImportance="Low"
      StandardErrorImportance="High"
      WorkingDirectory=".."
    />
  </Target>
</Project>
